<?php include "inc/html-top.inc";?>
	<body>
	<section class = "banner">
        <?php include "inc/header.inc"; ?>
        <?php include "inc/nav.inc"; ?>
	</section>

	<main>
		<div class="container">
            <p class="lead too-wide">The giraffe (Giraffa) is a genus of African even-toed ungulate mammals, the tallest living terrestrial animals and the largest ruminants. The genus currently consists of one species, Giraffa camelopardalis, the type species. Seven other species are extinct, prehistoric species known from fossils. Taxonomic classifications of one to eight extant giraffe species have been described, based upon research into the mitochondrial and nuclear DNA, as well as morphological measurements of Giraffa, but the IUCN currently recognises only one species with nine subspecies. The giraffe's chief distinguishing characteristics are its extremely long neck and legs, its horn-like ossicones, and its distinctive coat patterns. It is classified under the family Giraffidae, along with its closest extant relative, the okapi. Its scattered range extends from Chad in the north to South Africa in the south, and from Niger in the west to Somalia in the east. Giraffes usually inhabit savannahs and woodlands. Their food source is leaves, fruits and flowers of woody plants, primarily acacia species, which they browse at heights most other herbivores cannot reach. They may be preyed on by lions, leopards, spotted hyenas and African wild dogs. Giraffes live in herds of related females and their offspring, or bachelor herds of unrelated adult males, but are gregarious and may gather in large aggregations. Males establish social hierarchies through "necking", which are combat bouts where the neck is used as a weapon. Dominant males gain mating access to females, which bear the sole responsibility for raising the young.</p>

			<section class="l-fpattern">
			<h2>Taxonomy</h2>
			<div>
                <p>The giraffe is one of only two living genera of the family Giraffidae in the order Artiodactyla, the other being the okapi. The family was once much more extensive, with over 10 fossil genera described. Their closest known relatives are the extinct deer-like climacocerids. They, together with the family Antilocapridae (whose only extant species is the pronghorn), belong to the superfamily Giraffoidea. These animals may have evolved from the extinct family Palaeomerycidae which might also have been the ancestor of deer. The elongation of the neck appears to have started early in the giraffe lineage. Comparisons between giraffes and their ancient relatives suggest that vertebrae close to the skull lengthened earlier, followed by lengthening of vertebrae further down.[12] One early giraffid ancestor was Canthumeryx which has been dated variously to have lived 25–20 million years ago (mya), 17–15 mya or 18–14.3 mya and whose deposits have been found in Libya. This animal was medium-sized, slender and antelope-like. Giraffokeryx appeared 15 mya in the Indian subcontinent and resembled an okapi or a small giraffe, and had a longer neck and similar ossicones.[11] Giraffokeryx may have shared a clade with more massively built giraffids like Sivatherium and Bramatherium.</p>
                <p>In the early 19th century, Jean-Baptiste Lamarck believed the giraffe's long neck was an "acquired characteristic", developed as generations of ancestral giraffes strove to reach the leaves of tall trees.[19] This theory was eventually rejected, and scientists now believe the giraffe's neck arose through Darwinian natural selection—that ancestral giraffes with long necks thereby had a competitive feeding advantage (competing browsers hypothesis)[20] that better enabled them to survive and reproduce to pass on their genes. The giraffe genome is around 2.9 billion base pairs in length compared to the 3.3 billion base pairs of the okapi. Of the proteins in giraffe and okapi genes, 19.4% are identical. The two species are equally distantly related to cattle, suggesting the giraffe's unique characteristics are not because of faster evolution. The divergence of giraffe and okapi lineages dates to around 11.5 mya. A small group of regulatory genes in the giraffe appear to be responsible for the animal's stature and associated circulatory adaptations.</p>
                <p>The IUCN currently recognises only one species of giraffe with nine subspecies.[23][24] In 2001, a two-species taxonomy was proposed.[25] A 2007 study on the genetics of Giraffa, suggested they were six species: the West African, Rothschild's, reticulated, Masai, Angolan, and South African giraffe.[22] The study deduced from genetic differences in nuclear and mitochondrial DNA (mtDNA) that giraffes from these populations are reproductively isolated and rarely interbreed, though no natural obstacles block their mutual access. This includes adjacent populations of Rothschild's, reticulated, and Masai giraffes. The Masai giraffe was also suggested to consist of possibly two species separated by the Rift Valley.</p>
                <p>Reticulated and Masai giraffes have the highest mtDNA diversity, which is consistent with giraffes originating in eastern Africa. Populations further north are more closely related to the former, while those to the south are more related to the latter. Giraffes appear to select mates of the same coat type, which are imprinted on them as calves.[22] The implications of these findings for the conservation of giraffes were summarised by David Brown, lead author of the study, who told BBC News: "Lumping all giraffes into one species obscures the reality that some kinds of giraffe are on the brink. Some of these populations number only a few hundred individuals and need immediate protection." A 2011 study using detailed analyses of the morphology of giraffes, and application of the phylogenetic species concept, described eight species of living giraffes.[27] The eight species are: G. angolensis, G.antiquorum, G. camelopardalis, G. giraffa, G. peralta, G. reticulata, G. thornicrofti, and G. tippelskirchi.</p>
			</div>
			<div>
				<figure class="photo-frame">
					<img src="images/gtax.png" alt="Giraffe Locations">
					<figcaption>Approximate geographic ranges, fur patterns, and phylogenetic relationships between some giraffe subspecies based on mitochondrial DNA sequences. Colored dots on the map represent sampling localities. The phylogenetic tree is a maximum-likelihood phylogram based on samples from 266 giraffes. Asterisks along branches correspond to node values of more than 90% bootstrap support. Stars at branch tips identify paraphyletic haplotypes found in Maasai and reticulated giraffes</figcaption>
				</figure>
			</div>
			</section>

			<section class="l-fpattern">
            <h2>Characteristics</h2>
            <div>
			    <p>OFully grown giraffes stand 4.3–5.7 m (14.1–18.7 ft) tall, with males taller than females.[47][48][49] The tallest recorded male was 5.88 m (19.3 ft) and the tallest recorded female was 5.17 m (17.0 ft) tall.[47][50] The average weight is 1,192 kg (2,628 lb) for an adult male and 828 kg (1,825 lb) for an adult female[51] with maximum weights of 1,930 kg (4,250 lb) and 1,180 kg (2,600 lb) having been recorded for males and females, respectively.[48][49] Despite its long neck and legs, the giraffe's body is relatively short.[52]:66 Located at both sides of the head, the giraffe's large, bulging eyes give it good all-round vision from its great height.[53]:25 Giraffes see in colour[53]:26 and their senses of hearing and smell are also sharp.[19] The animal can close its muscular nostrils to protect against sandstorms and ants.</p>
                <p>The coat has dark blotches or patches (which can be orange, chestnut, brown, or nearly black in colour[19]) separated by light hair (usually white or cream in colour[19]). Male giraffes become darker as they age.[45] The coat pattern has been claimed to serve as camouflage in the light and shade patterns of savannah woodlands.[46] While adult giraffes standing among trees and bushes are hard to see at even a few metres' distance, they actively move into the open to gain the best view of an approaching predator, obviating any benefit that camouflage might bring. Instead, the adults rely on their size and ability to defend themselves. However, camouflage appears to be important for calves, which spend a large part of the day in hiding, away from their mothers; further, over half of all calves die within a year, so predation is certainly important. It appears, therefore, that the spotted coat of the giraffe functions as camouflage for the young, while adults simply inherit this coloration as a by-product.[11] The skin underneath the dark areas may serve as windows for thermoregulation, being sites for complex blood vessel systems and large sweat glands.[54] Each individual giraffe has a unique coat pattern.</p>
                <p>Both sexes have prominent horn-like structures called ossicones, which are formed from ossified cartilage, covered in skin and fused to the skull at the parietal bones.[45] Being vascularized, the ossicones may have a role in thermoregulation,[54] and are also used in combat between males.[56] Appearance is a reliable guide to the sex or age of a giraffe: the ossicones of females and young are thin and display tufts of hair on top, whereas those of adult males end in knobs and tend to be bald on top.[45] Also, a median lump, which is more prominent in males, emerges at the front of the skull.[7] Males develop calcium deposits that form bumps on their skulls as they age.[19] A giraffe's skull is lightened by multiple sinuses.[52]:70 However, as males age, their skulls become heavier and more club-like, helping them become more dominant in combat.[45] The upper jaw has a grooved palate and lacks front teeth.[53]:26 The giraffe's molars have a rough surface.</p>
            </div>
			<div>
				<figure class="right photo-frame">
					<img src="images/glook.jpg" alt="Closeup of the head of a giraffe at the Melbourne Zoo">
					<figcaption>Closeup of the head of a giraffe at the Melbourne Zoo</figcaption>
				</figure>
			</div>
			</section>

			<section class="l-fpattern">
			<h2>Behavior and Ecology</h2>
            <div>
			    <p>Giraffes usually inhabit savannahs and open woodlands. They prefer Acacieae, Commiphora, Combretum and open Terminalia woodlands over denser environments like Brachystegia woodlands.[40]:322 The Angolan giraffe can be found in desert environments.[83] Giraffes browse on the twigs of trees, preferring trees of the subfamily Acacieae and the genera Commiphora and Terminalia,[4] which are important sources of calcium and protein to sustain the giraffe's growth rate.[11] They also feed on shrubs, grass and fruit.[40]:324 A giraffe eats around 34 kg (75 lb) of foliage daily.[45] When stressed, giraffes may chew the bark off branches. Although herbivorous, the giraffe has been known to visit carcasses and lick dried meat off bones.</p>
                <p>During the wet season, food is abundant and giraffes are more spread out, while during the dry season, they gather around the remaining evergreen trees and bushes.[4] Mothers tend to feed in open areas, presumably to make it easier to detect predators, although this may reduce their feeding efficiency.[70] As a ruminant, the giraffe first chews its food, then swallows it for processing and then visibly passes the half-digested cud up the neck and back into the mouth to chew again.[52]:78–79 It is common for a giraffe to salivate while feeding.[53]:27 The giraffe requires less food than many other herbivores because the foliage it eats has more concentrated nutrients and it has a more efficient digestive system.[4] The animal's faeces come in the form of small pellets.[7] When it has access to water, a giraffe drinks at intervals no longer than three days.</p>
                <p>Giraffe groups tend to be sex-segregated[88] although mixed-sex groups made of adult females and young males are known to occur. Particularity stable giraffe groups are those made of mothers and their young,[85] which can last weeks or months.[89] Social cohesion in these groups is maintained by the bonds formed between calves.[40]:330[85] Female association appears to be based on space-use and individuals may be matrilineally related.[88] In general, females are more selective than males in who they associate with in regards to individuals of the same sex.[87] Young males also form groups and will engage in playfights. However, as they get older males become more solitary but may also associate in pairs or with female groups.[88][89] Giraffes are not territorial,[7] but they have home ranges.[45] Male giraffes occasionally wander far from areas that they normally frequent.</p>
            </div>
            <div>
				<figure class="right photo-frame">
					<img src="images/ggroup.jpg" alt="Group of giraffe">
					<figcaption>Gathering of female southern giraffes in Tswalu Kalahari Reserve, South Africa. These animals commonly gather in herds.</figcaption>
				</figure>
			</div>
			</section>

		<?php include "inc/footer.inc"; ?>
		</div> <!--.container -->
		<?php include "inc/scripts.inc"; ?>
	</body>
</html>