<?php include "inc/html-top.inc";?>
	<body>
	<section class = "banner">
        <?php include "inc/header.inc"; ?>
        <?php include "inc/nav.inc"; ?>
	</section>
	<main>
		<div class="container">
            <p class="lead too-wide">The lion (Panthera leo) is a species in the family Felidae and a member of the genus Panthera. It is the second largest extant species after the tiger. It exhibits a pronounced sexual dimorphism; males are larger than females with a typical weight range of 150 to 250 kg (331 to 551 lb) for the former and 120 to 182 kg (265 to 401 lb) for the latter. In addition, male lions have a prominent mane, which is the most recognisable feature of the species. Both sexes have hairy tufts at the end of their tails. The lion typically inhabits grasslands and savannahs, but is absent in dense forests. It is usually more diurnal than other big cats, but when persecuted adapts to being active at night and at twilight. A lion pride consists of a few adult males, related females and cubs. Prides vary in size and composition from three to 20 adult lions, depending on habitat and prey availability. Females cooperate when hunting and prey mostly on large ungulates, including antelope, deer, buffalo, zebra and even giraffe.</p>

			<section class="l-fpattern">
			<h2>Taxonomy</h2>
			<div>
                <p>The lion's closest relatives are the other species of the genus Panthera: the tiger, snow leopard, jaguar, and leopard. Results of phylogenetic studies published in 2006 and 2009 indicated that the jaguar and the lion belong to one sister group, which diverged about 2.06 million years ago.[7][8] Results of later studies published in 2010 and 2011 indicate that the leopard and the lion belong to the same sister group, which diverged 1.95–3.10 million years ago.[9][10] The lion and the snow leopard diverged about 2.1 million years ago.[11]</p>
                <p>In 1758, Carl Linnaeus described the lion in his work Systema Naturae and gave it the scientific name Felis leo.[3] Between the mid 18th and mid 20th centuries, 26 lion specimens were described and proposed as subspecies, of which 11 were recognised as valid in 2005.[1] They were distinguished on the basis of appearance, size and colour of mane. As these characteristics vary highly between individuals, most of these forms were probably not true subspecies, especially as they were often based upon museum material with "striking, but abnormal" morphological characteristics. Based on morphology of 58 lion skulls in three European museums, the subspecies krugeri, nubica, persica, and senegalensis were assessed distinct; but bleyenberghi overlapped with senegalensis and krugeri. The Asiatic lion persica was the most distinctive, and the Cape lion had characteristics allying it more with P. l. persica than the other sub-Saharan lions.[13] Until 2016, eight subspecies were accepted and considered valid.[14][15]</p>
                <p>TEarly phylogenetic research was focused on lions from eastern and southern parts of Africa, and already showed that they can possibly be divided in two main clades: one to the west of the Great Rift Valley and the other to the east. Lions in eastern Kenya are genetically much closer to lions in Southern Africa than to lions in the Aberdare National Park in western Kenya. In a subsequent study, tissue and bone samples of 32 lion specimens in museums were used. Results indicated that lions form three phylogeographic groups, one each in North Africa and Asia, in Central Africa and in Southern Africa. Samples of 53 lions, both wild and captive individuals, from 15 countries were used for phylogenetic analysis. Results showed little genetic diversity between lions from Asia, West and Central Africa, whereas lions from East Africa were genetically closer to lions from Southern Africa. Results of another phylogeographic study indicate that southeastern Ethiopia, western Somalia and northern Kenya are genetic admixture regions between lions from Central Africa and Southern Africa, and that lions in the northern part of Central Africa are genetically closer to lions in North and West Africa, and those in the southern part of Central Africa closer to lions in Southern Africa.[19]</p>
			</div>
			<div>
				<figure class="photo-frame">
					<img src="images/liontax.png" alt="Location of lion species">
					<figcaption>Range map showing lion subspecies that were considered valid in the late 20th century.</figcaption>
				</figure>
			</div>
			</section>

			<section class="l-fpattern">
            <h2>Characteristics</h2>
            <div>
			    <p>The lion is a muscular, deep-chested cat with a short, rounded head, a reduced neck and round ears. The colour of its fur varies from light buff to silverly gray, to yellowish red and dark brown.[62] The underparts are generally lighter, and cubs are born with dark spots on their bodies. The spots fade as lions reach adulthood, although faint spots often may still be seen on the legs and underparts. The lion is the only member of the cat family that displays obvious sexual dimorphism. Males are more robust than females, have broader heads and a prominent mane, which grows downward and backward and covers most of the head, neck, shoulders, and chest. The mane is typically brownish and tinged with yellow, rust, and black hairs. The most distinctive characteristic shared by both females and males is that the tail ends in a dark, hairy tuft. In some lions, the tuft conceals a hard "spine" or "spur", approximately 5 mm (0.20 in) long, formed of the final sections of tail bone fused together. The lion is the only cat with a tufted tail, but the function of the tuft and spine are unknown. Absent at birth, the tuft develops around ​5 1⁄2 months of age and is readily identifiable at the age of seven months.[63]</p>
                <p>The lion's mane is the most recognisable feature of the species.[31] The mane starts growing when lions are about one year old. Mane colour varies, and darkens with age. Research results indicate that environmental factors such as average ambient temperature influence the mane's colour and size. Mane length apparently signals fighting success in male–male relationships. Darker-maned individuals may have longer reproductive lives and higher offspring survival, although they suffer in the hottest months of the year. The presence, absence, colour, and size of the mane is associated with genetic precondition, sexual maturity, climate, and testosterone production; the rule of thumb is the darker and fuller the mane, the healthier the lion. In the Serengeti National Park, female lions favour males as mates with dense, dark manes.[74][75] The main purpose of the mane is thought to protect the lion's neck and throat in territorial fights with rivals.</p>
                <p>The lion is a generalist hypercarnivore[104] and usually hunts in groups. Its prey consists mainly of mammals, particularly ungulates, with a preference for wildebeest, zebras, buffalo, gemsbok, and giraffes in Africa,[105] and chital, sambar deer, nilgai, wild boar, chinkara and chousingha in India.[106] Because of its wide prey spectrum, the lion is considered to be an apex and keystone predator.[107] African lions prefer prey weighing 190–550 kg (420–1,210 lb).[105] They generally avoid fully grown adult elephants, hippopotamuses and rhinoceroses, as well as very small prey like dik-dik, hyrax, hare and vervet monkey.[108] However, Thomson's gazelles may be hunted[109] and warthogs are often taken depending on availability, despite being below the preferred weight range.[105] In many areas, a small number of species may make up around three-fourths of the lion's diet. In Serengeti National Park, wildebeest, zebras and gazelle are the majority of prey.[110] In Kruger National Park, giraffes are the most common prey.[111] In Manyara Park, Cape buffaloes constitute as much as 62% of the lion's diet.[112] In the Okavango Delta, with its strong seasonal changes in prey, up to eight species may make up three quarters of a lion's diet.[110] Occasionally adult hippopotamus are taken at Gorongosa National Park and calves are commonly hunted at Virunga National Park. In addition to size, the aquatic nature of hippos makes them normally unavailable as prey.[104] The lions of Savuti, Botswana, have adapted to hunting young elephants during the dry season, and a pride of 30 lions has been recorded killing individuals between the ages of four and eleven years. Occasionally, even adult elephants are taken, and due to their immense size compared to lions, the ratio of prey to predator size for the lion is 10–15 : 1, the highest for any known terrestrial mammalian predator.[113] Lions also attack domestic livestock and in India cattle contribute significantly to their diet.[77][106] Unusual prey items include porcupines and small reptiles. Lions will kill other predators such as leopards, cheetahs, and hyenas, but they seldom devour them.</p>
            </div>
			<div>
				<figure class="right photo-frame">
					<img src="images/lionlook.jpg" alt="A male Southern African lion in the area of Okonjima, Namibia">
					<figcaption>A male Southern African lion in the area of Okonjima, Namibia </figcaption>
				</figure>
			</div>
			</section>

			<section class="l-fpattern">
			<h2>Behavior and Ecology</h2>
            <div>
			    <p>Of all wild cat species, the lion is the most social cat, living in groups of related individuals with their offspring. Such a group is called a pride. Male lion groups are called a coalition.[88] Females form the stable social unit in a pride and do not tolerate outside females.[89] Membership only changes with the births and deaths of lionesses,[90] although some females leave and become nomadic.[91] The average pride consists of around 15 lions, including several adult females and up to four males and their cubs of both sexes. Large prides, consisting of up to 30 individuals, have also been observed.[92] The sole exception to this pattern is the Tsavo lion pride which always has just one adult male.[93] Male cubs are excluded from their maternal pride when they reach maturity at around 2–3 years of age.</p>
                <p>The area a pride occupies is called a pride area, whereas that by a nomad is a range.[88] The males associated with a pride tend to stay on the fringes, patrolling their territory. Why sociality – the most pronounced in any cat species – has developed in lionesses is the subject of much debate. Increased hunting success appears an obvious reason, but this is less than sure upon examination: coordinated hunting does allow for more successful predation but also ensures that non-hunting members reduce per capita calorific intake; however, some take a role raising cubs, who may be left alone for extended periods of time. Members of the pride regularly tend to play the same role in hunts and hone their skills. The health of the hunters is the primary need for the survival of the pride, and they are the first to consume the prey at the site it is taken. Other benefits include possible kin selection (better to share food with a related lion than with a stranger), protection of the young, maintenance of territory, and individual insurance against injury and hunger.</p>
                <p>Young lions first display stalking behaviour around three months of age, although they do not participate in hunting until they are almost a year old. They begin to hunt effectively when nearing the age of two.[115] Single lions are capable of bringing down prey like zebra and wildebeest, which can be twice their own weight, while hunting larger prey like giraffes and buffalo alone is too much of a risk. Cooperative-hunting lions are usually successful.[94][109] In prides, lionesses do most of the hunting.[94] In typical hunts, each lioness has a favoured position in the group, either stalking prey on the "wing" then attacking, or moving a smaller distance in the centre of the group and capturing prey in flight from other lionesses. Males attached to prides do not usually participate in group hunting.[116] However, some evidence suggests that pride males are just as successful as females; they are solo hunters who ambush prey in small bush.[117] Lions are not particularly known for their stamina – for instance, a lioness' heart makes up only 0.57% of her body weight (a male's is about 0.45% of his body weight), whereas a hyena's heart is close to 1% of its body weight.[118] Thus, they only run fast in short bursts,[119] and need to be close to their prey before starting the attack. They take advantage of factors that reduce visibility; many kills take place near some form of cover or at night.[120] In addition, since lions are such ambush hunters, humans farming in the vicinity have recently found that lions are easily discouraged if they think their prey has spotted them. To protect their cattle from such attacks with that knowledge in mind, farmers have found that all that they have to do is simply paint eyes on the hindquarters of each cow, which is usually enough for hunting lions to think they are spotted and move to easier prey.</p>
            </div>
            <div>
				<figure class="right photo-frame">
					<img src="images/lionteeth.jpg" alt="Lion teeth">
					<figcaption>A lion's teeth are typical of a carnivore</figcaption>
				</figure>
			</div>
			</section>

		<?php include "inc/footer.inc"; ?>
		</div> <!--.container -->
		<?php include "inc/scripts.inc"; ?>
	</body>
</html>