<header>
	<div class="container">
		<div class="primary">
			<a href="index.php"><img src="images/logo.png" alt="Bear logo"></a>
		</div>
		<div class="big-message">
			<a href="index.php"><h1>Mexico</h1></a>
		</div>
		<div class="strong">
			<form method="post" action="welcome.php">
				<label class="stand-alone" for="email">Sign-up for our Newsletter</label>
				<input type="text" name="email" id="email">
				<input type="submit" value="Sign-up">
			</form>
		</div>
	</div><!-- .container -->
</header>